### ISSUE TITLE
ModuleNotFoundError: No module named 'spiritfire'

### ISSUE THREAD

**Issue by rcox771** [Xellophane/SpiritualFire#1]
Not much of a django guy - is this the correct entrypoint?
```
(py39) C:\Users\russ7\code\SpiritualFire>python SpiritFire/manage.py check
Traceback (most recent call last):
  File "C:\Users\russ7\code\SpiritualFire\SpiritFire\manage.py", line 21, in <module>
    main()
  File "C:\Users\russ7\code\SpiritualFire\SpiritFire\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\russ7\miniconda3\envs\py39\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\russ7\miniconda3\envs\py39\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\russ7\miniconda3\envs\py39\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\russ7\miniconda3\envs\py39\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\russ7\miniconda3\envs\py39\lib\site-packages\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "C:\Users\russ7\miniconda3\envs\py39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'spiritfire'

```

**Comment by Xellophane** [comment]
Verified bug, also present with runserver. Gimme 30 to fix it.

**Comment by Xellophane** [comment]
`INSTALLED_APPS = [
    'spiritfire.landing',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]`

`INSTALLED_APPS = [
    'landing.apps.LandingConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]`

Has been changed to fix this bug. As soon as I figure out how to merge this back without breaking everything I'll do so.

**Comment by rcox771** [comment]
Alrighty. Ill test it out Friday or Saturday
